FROM python:3.10

RUN apt-get update && apt-get install -y supervisor \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY pyproject.toml poetry.lock /app/
RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root
COPY .env /app/.env
COPY bot/ /app/bot
COPY supervisord.bot.conf /etc/supervisor/conf.d/supervisord.bot.conf

ENV PYTHONPATH=/app


CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.bot.conf"]