services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: token_utils:7-alpine
    container_name: token_utils
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - backend
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile.app
#    volumes:
#      - ./web:/app/web
#    ports:
#      - "5000:5000"
#    depends_on:
#      - db
#    networks:
#      - backend
#    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.app.conf"]
#
#  bot:
#    build:
#      context: .
#      dockerfile: Dockerfile.bot
#    volumes:
#      - ./bot:/app/bot
#    depends_on:
#      - app
#    networks:
#      - backend
#    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.bot.conf"]

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  redis_data: